id: A9A85CC5A
title: Guru Yoga of Lord Marpa Lotsāwa
type: translation
pechas:
- IE7887048
- I8EDDC1D1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:01:19.928265
  last_modified_at: 2023-01-04 13:01:19.928284
  collections:
  - Marpa Lotsāwa Series
  - Works of Tibetan Masters
alignment_to_base:
  IE7887048/612E: 507E
  I8EDDC1D1/1821: 507E
